// packages/angular/src/components/card.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalCardVariant = 'default' | 'elevated' | 'outlined' | 'ghost';
export type HilalCardPadding = 'none' | 'sm' | 'md' | 'lg';

@Component({
  selector: 'hilal-card',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<article [class]="classes()"><ng-content></ng-content></article>`,
})
export class HilalCardComponent {
  @Input() variant: HilalCardVariant = 'default';
  @Input() padding: HilalCardPadding = 'md';
  @Input() interactive = false;

  protected readonly classes = computed(() => {
    const parts = ['hilal-card', `hilal-card--${this.variant}`];
    if (this.padding !== 'none') parts.push(`hilal-card--${this.padding}`);
    if (this.interactive) parts.push('hilal-card--interactive');
    return parts.join(' ');
  });
}

@Component({
  selector: 'hilal-card-header',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<header class="hilal-card__header"><ng-content></ng-content></header>`,
})
export class HilalCardHeaderComponent {}

@Component({
  selector: 'hilal-card-body',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="hilal-card__body"><ng-content></ng-content></div>`,
})
export class HilalCardBodyComponent {}

@Component({
  selector: 'hilal-card-footer',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<footer class="hilal-card__footer"><ng-content></ng-content></footer>`,
})
export class HilalCardFooterComponent {}

// packages/react/src/components/card.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const cardVariants = cva('hilal-card', {
  variants: {
    variant: {
      default:  'hilal-card--default',
      elevated: 'hilal-card--elevated',
      outlined: 'hilal-card--outlined',
      ghost:    'hilal-card--ghost',
    },
    padding: {
      none: '',
      sm: 'hilal-card--sm',
      md: 'hilal-card--md',
      lg: 'hilal-card--lg',
    },
    interactive: { true: 'hilal-card--interactive', false: '' },
  },
  defaultVariants: { variant: 'default', padding: 'md', interactive: false },
});

export interface CardProps
  extends HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {}

export const Card = forwardRef<HTMLDivElement, CardProps>(function Card(
  { variant, padding, interactive, className, ...rest },
  ref,
) {
  return <article ref={ref} className={cn(cardVariants({ variant, padding, interactive }), className)} {...rest} />;
});

export const CardHeader = forwardRef<HTMLElement, HTMLAttributes<HTMLElement>>(function CardHeader(
  { className, ...rest },
  ref,
) {
  return <header ref={ref} className={cn('hilal-card__header', className)} {...rest} />;
});

export const CardBody = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(function CardBody(
  { className, ...rest },
  ref,
) {
  return <div ref={ref} className={cn('hilal-card__body', className)} {...rest} />;
});

export const CardFooter = forwardRef<HTMLElement, HTMLAttributes<HTMLElement>>(function CardFooter(
  { className, ...rest },
  ref,
) {
  return <footer ref={ref} className={cn('hilal-card__footer', className)} {...rest} />;
});
