// packages/angular/src/components/checkbox.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalCheckboxSize = 'sm' | 'md';

@Component({
  selector: 'hilal-checkbox',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [class]="classes()">
      <input type="checkbox" class="hilal-check__input" [checked]="checked" [disabled]="disabled" />
      <span class="hilal-check__box" aria-hidden="true">
        <svg class="hilal-check__tick" viewBox="0 0 16 16" focusable="false">
          <path d="M3 8l3 3 7-7" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </span>
      <span *ngIf="label" class="hilal-check__label">{{ label }}</span>
    </label>
  `,
})
export class HilalCheckboxComponent {
  @Input() size: HilalCheckboxSize = 'md';
  @Input() checked = false;
  @Input() disabled = false;
  @Input() label?: string;

  protected readonly classes = computed(() => `hilal-check hilal-check--${this.size}`);
}

// packages/react/src/components/checkbox.tsx
import { forwardRef, useEffect, useRef, useImperativeHandle, type InputHTMLAttributes, type ReactNode } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const checkboxVariants = cva('hilal-check', {
  variants: { size: { sm: 'hilal-check--sm', md: 'hilal-check--md' } },
  defaultVariants: { size: 'md' },
});

export interface CheckboxProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type'>,
    VariantProps<typeof checkboxVariants> {
  indeterminate?: boolean;
  children?: ReactNode;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { size, indeterminate, children, className, ...rest },
  ref,
) {
  const inputRef = useRef<HTMLInputElement>(null);
  useImperativeHandle(ref, () => inputRef.current!, []);

  useEffect(() => {
    if (inputRef.current) inputRef.current.indeterminate = indeterminate ?? false;
  }, [indeterminate]);

  return (
    <label className={cn(checkboxVariants({ size }), className)}>
      <input ref={inputRef} type="checkbox" className="hilal-check__input" {...rest} />
      <span className="hilal-check__box" aria-hidden>
        <svg className="hilal-check__tick" viewBox="0 0 16 16" focusable="false">
          {indeterminate ? (
            <line x1="3" y1="8" x2="13" y2="8" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round" />
          ) : (
            <path d="M3 8l3 3 7-7" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round" strokeLinejoin="round" />
          )}
        </svg>
      </span>
      {children ? <span className="hilal-check__label">{children}</span> : null}
    </label>
  );
});
