// packages/angular/src/components/input.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalInputSize = 'sm' | 'md' | 'lg';
export type HilalInputState = 'default' | 'error' | 'success' | 'disabled';

@Component({
  selector: 'hilal-input',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="fieldClasses()" [attr.data-state]="resolvedState()">
      <label *ngIf="label" class="hilal-field__label" [attr.for]="inputId">{{ label }}</label>
      <div class="hilal-field__control">
        <span *ngIf="leadingIcon" class="hilal-field__icon hilal-field__icon--leading" aria-hidden="true">{{ leadingIcon }}</span>
        <input
          class="hilal-input"
          [id]="inputId"
          [type]="type"
          [placeholder]="placeholder"
          [disabled]="disabled"
          [value]="value"
          [attr.aria-invalid]="!!error"
        />
        <span *ngIf="trailingIcon" class="hilal-field__icon hilal-field__icon--trailing" aria-hidden="true">{{ trailingIcon }}</span>
      </div>
      <p *ngIf="message()" class="hilal-field__hint">{{ message() }}</p>
    </div>
  `,
})
export class HilalInputComponent {
  @Input() size: HilalInputSize = 'md';
  @Input() label?: string;
  @Input() hint?: string;
  @Input() error?: string;
  @Input() success?: string;
  @Input() type = 'text';
  @Input() placeholder = '';
  @Input() value = '';
  @Input() disabled = false;
  @Input() leadingIcon?: string;
  @Input() trailingIcon?: string;
  @Input() inputId = `hilal-input-${Math.random().toString(36).slice(2, 9)}`;

  protected readonly fieldClasses = computed(() => `hilal-field hilal-field--${this.size}`);
  protected readonly resolvedState = computed<HilalInputState>(() =>
    this.error ? 'error' : this.success ? 'success' : this.disabled ? 'disabled' : 'default',
  );
  protected readonly message = computed(() => this.error ?? this.success ?? this.hint ?? '');
}

// packages/react/src/components/input.tsx
import { forwardRef, useId, type InputHTMLAttributes, type ReactNode } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const fieldVariants = cva('hilal-field', {
  variants: {
    size: { sm: 'hilal-field--sm', md: 'hilal-field--md', lg: 'hilal-field--lg' },
  },
  defaultVariants: { size: 'md' },
});

export interface InputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof fieldVariants> {
  label?: string;
  hint?: string;
  error?: string;
  success?: string;
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
  containerClassName?: string;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(function Input(
  {
    label,
    hint,
    error,
    success,
    leadingIcon,
    trailingIcon,
    size,
    id,
    className,
    containerClassName,
    disabled,
    ...rest
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const state = error ? 'error' : success ? 'success' : disabled ? 'disabled' : 'default';
  const message = error ?? success ?? hint;

  return (
    <div className={cn(fieldVariants({ size }), containerClassName)} data-state={state}>
      {label ? (
        <label className="hilal-field__label" htmlFor={inputId}>
          {label}
        </label>
      ) : null}
      <div className="hilal-field__control">
        {leadingIcon ? (
          <span className="hilal-field__icon hilal-field__icon--leading" aria-hidden>
            {leadingIcon}
          </span>
        ) : null}
        <input
          ref={ref}
          id={inputId}
          className={cn('hilal-input', className)}
          disabled={disabled}
          aria-invalid={!!error}
          aria-describedby={message ? `${inputId}-msg` : undefined}
          {...rest}
        />
        {trailingIcon ? (
          <span className="hilal-field__icon hilal-field__icon--trailing" aria-hidden>
            {trailingIcon}
          </span>
        ) : null}
      </div>
      {message ? (
        <p id={`${inputId}-msg`} className="hilal-field__hint">
          {message}
        </p>
      ) : null}
    </div>
  );
});
