// packages/angular/src/components/toggle.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalToggleSize = 'sm' | 'md';

@Component({
  selector: 'hilal-toggle',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [class]="classes()">
      <input type="checkbox" role="switch" class="hilal-toggle__input" [checked]="checked" [disabled]="disabled" />
      <span class="hilal-toggle__track" aria-hidden="true">
        <span class="hilal-toggle__thumb"></span>
      </span>
      <span *ngIf="label" class="hilal-toggle__label">{{ label }}</span>
    </label>
  `,
})
export class HilalToggleComponent {
  @Input() size: HilalToggleSize = 'md';
  @Input() checked = false;
  @Input() disabled = false;
  @Input() label?: string;

  protected readonly classes = computed(() => `hilal-toggle hilal-toggle--${this.size}`);
}

// packages/react/src/components/toggle.tsx
import { forwardRef, type InputHTMLAttributes, type ReactNode } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const toggleVariants = cva('hilal-toggle', {
  variants: { size: { sm: 'hilal-toggle--sm', md: 'hilal-toggle--md' } },
  defaultVariants: { size: 'md' },
});

export interface ToggleProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type' | 'role'>,
    VariantProps<typeof toggleVariants> {
  children?: ReactNode;
}

export const Toggle = forwardRef<HTMLInputElement, ToggleProps>(function Toggle(
  { size, children, className, ...rest },
  ref,
) {
  return (
    <label className={cn(toggleVariants({ size }), className)}>
      <input ref={ref} type="checkbox" role="switch" className="hilal-toggle__input" {...rest} />
      <span className="hilal-toggle__track" aria-hidden>
        <span className="hilal-toggle__thumb" />
      </span>
      {children ? <span className="hilal-toggle__label">{children}</span> : null}
    </label>
  );
});
