// packages/react/src/components/bottomnav.tsx
import { forwardRef, type HTMLAttributes, type AnchorHTMLAttributes, type ReactNode } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const bottomNavVariants = cva('hilal-bottomnav', {
  variants: { variant: { default: '', floating: 'hilal-bottomnav--floating' } },
  defaultVariants: { variant: 'default' },
});

export interface BottomNavProps
  extends HTMLAttributes<HTMLElement>,
    VariantProps<typeof bottomNavVariants> {
  ariaLabel?: string;
}

export const BottomNav = forwardRef<HTMLElement, BottomNavProps>(function BottomNav(
  { variant, ariaLabel = 'Primary', className, ...rest }, ref,
) {
  return <nav ref={ref} className={cn(bottomNavVariants({ variant }), className)} aria-label={ariaLabel} {...rest} />;
});

export interface BottomNavItemProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  icon?: ReactNode;
  label: ReactNode;
  active?: boolean;
}

export const BottomNavItem = forwardRef<HTMLAnchorElement, BottomNavItemProps>(function BottomNavItem(
  { icon, label, active, className, ...rest }, ref,
) {
  return (
    <a ref={ref} className={cn('hilal-bottomnav__item', className)} aria-current={active ? 'page' : undefined} {...rest}>
      {icon ? <span className="hilal-bottomnav__icon" aria-hidden>{icon}</span> : null}
      <span className="hilal-bottomnav__label">{label}</span>
    </a>
  );
});

// packages/angular/src/components/bottomnav.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalBottomNavVariant = 'default' | 'floating';

@Component({
  selector: 'hilal-bottomnav',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<nav [class]="classes()" [attr.aria-label]="ariaLabel"><ng-content></ng-content></nav>`,
})
export class HilalBottomNavComponent {
  @Input() variant: HilalBottomNavVariant = 'default';
  @Input() ariaLabel = 'Primary';

  protected readonly classes = computed(() =>
    this.variant === 'floating' ? 'hilal-bottomnav hilal-bottomnav--floating' : 'hilal-bottomnav',
  );
}

@Component({
  selector: 'hilal-bottomnav-item',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <a class="hilal-bottomnav__item" [href]="href" [attr.aria-current]="active ? 'page' : null">
      <span *ngIf="icon" class="hilal-bottomnav__icon" aria-hidden="true">{{ icon }}</span>
      <span class="hilal-bottomnav__label">{{ label }}</span>
    </a>
  `,
})
export class HilalBottomNavItemComponent {
  @Input() href = '#';
  @Input() icon?: string;
  @Input() label = '';
  @Input() active = false;
}
