// packages/react/src/components/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const buttonVariants = cva('hilal-btn', {
  variants: {
    variant: {
      primary: 'hilal-btn--primary',
      secondary: 'hilal-btn--secondary',
      tertiary: 'hilal-btn--tertiary',
    },
    size: {
      sm: 'hilal-btn--sm',
      md: 'hilal-btn--md',
      lg: 'hilal-btn--lg',
    },
  },
  defaultVariants: {
    variant: 'primary',
    size: 'md',
  },
});

export interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  loading?: boolean;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  { className, variant, size, loading, disabled, children, ...rest },
  ref,
) {
  return (
    <button
      ref={ref}
      className={cn(buttonVariants({ variant, size }), className)}
      disabled={disabled || loading}
      data-state={loading ? 'loading' : undefined}
      {...rest}
    >
      {loading ? <span className="hilal-btn__spinner" aria-hidden /> : null}
      {children}
    </button>
  );
});

// packages/angular/src/components/button.component.ts
import { Component, Input, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalButtonVariant = 'primary' | 'secondary' | 'tertiary';
export type HilalButtonSize = 'sm' | 'md' | 'lg';

/**
 * Hilal Button (Angular)
 * Emits the same DOM as @hilal-ds/react and hilal/blade — relies on @hilal-ds/core CSS.
 *
 *   <hilal-button variant="primary" size="md">Click me</hilal-button>
 */
@Component({
  selector: 'hilal-button',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      [class]="classes()"
      [disabled]="disabled || loading"
      [attr.data-state]="loading ? 'loading' : null"
    >
      <span *ngIf="loading" class="hilal-btn__spinner" aria-hidden="true"></span>
      <ng-content></ng-content>
    </button>
  `,
})
export class HilalButtonComponent {
  @Input() variant: HilalButtonVariant = 'primary';
  @Input() size: HilalButtonSize = 'md';
  @Input() disabled = false;
  @Input() loading = false;

  protected readonly classes = computed(() =>
    ['hilal-btn', `hilal-btn--${this.variant}`, `hilal-btn--${this.size}`].join(' '),
  );
}
