// packages/react/src/components/combobox.tsx
import {
  forwardRef, useId, useState, useRef, useEffect, useMemo, useCallback,
  type KeyboardEvent, type HTMLAttributes,
} from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn.js';

const fieldVariants = cva('hilal-field hilal-combobox', {
  variants: { size: { sm: 'hilal-field--sm', md: 'hilal-field--md', lg: 'hilal-field--lg' } },
  defaultVariants: { size: 'md' },
});

export interface ComboboxOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ComboboxProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'>,
    VariantProps<typeof fieldVariants> {
  options: ComboboxOption[];
  value?: string;
  onChange?: (value: string) => void;
  label?: string;
  hint?: string;
  error?: string;
  placeholder?: string;
  disabled?: boolean;
  /** Custom filter. Defaults to case-insensitive substring on label. */
  filter?: (option: ComboboxOption, query: string) => boolean;
  /** Shown when filtered list is empty. */
  emptyMessage?: string;
}

const defaultFilter = (option: ComboboxOption, query: string): boolean =>
  option.label.toLowerCase().includes(query.toLowerCase());

export const Combobox = forwardRef<HTMLDivElement, ComboboxProps>(function Combobox(
  {
    options, value, onChange, label, hint, error, placeholder = 'Select…',
    size, disabled, filter = defaultFilter, emptyMessage = 'No results',
    className, id, ...rest
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const listboxId = `${inputId}-listbox`;

  const selected = useMemo(() => options.find((o) => o.value === value), [options, value]);
  const [query, setQuery] = useState(selected?.label ?? '');
  const [open, setOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => { setQuery(selected?.label ?? ''); }, [selected]);

  const filtered = useMemo(
    () => (open && query !== (selected?.label ?? '') ? options.filter((o) => filter(o, query)) : options),
    [options, filter, query, open, selected],
  );

  // close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const commit = useCallback((opt: ComboboxOption) => {
    if (opt.disabled) return;
    onChange?.(opt.value);
    setQuery(opt.label);
    setOpen(false);
    inputRef.current?.focus();
  }, [onChange]);

  const onKey = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!open) setOpen(true);
      setActiveIndex((i) => Math.min(i + 1, filtered.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIndex((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const opt = filtered[activeIndex];
      if (opt) commit(opt);
    } else if (e.key === 'Escape') {
      setOpen(false);
      setQuery(selected?.label ?? '');
    } else if (e.key === 'Tab') {
      setOpen(false);
    }
  };

  const state = error ? 'error' : disabled ? 'disabled' : 'default';
  const message = error ?? hint;

  return (
    <div ref={(node) => { wrapRef.current = node; if (typeof ref === 'function') ref(node); else if (ref) ref.current = node; }}
      className={cn(fieldVariants({ size }), className)} data-state={state} {...rest}>
      {label ? <label className="hilal-field__label" htmlFor={inputId}>{label}</label> : null}
      <div className="hilal-field__control hilal-combobox__control">
        <input
          ref={inputRef}
          id={inputId}
          className="hilal-input hilal-combobox__input"
          role="combobox"
          aria-expanded={open}
          aria-controls={listboxId}
          aria-autocomplete="list"
          aria-activedescendant={open && filtered[activeIndex] ? `${listboxId}-${activeIndex}` : undefined}
          placeholder={placeholder}
          value={query}
          disabled={disabled}
          onChange={(e) => { setQuery(e.target.value); setOpen(true); setActiveIndex(0); }}
          onFocus={() => setOpen(true)}
          onKeyDown={onKey}
        />
        <span className="hilal-select__chevron" aria-hidden>▾</span>
      </div>
      {open && !disabled ? (
        <ul id={listboxId} className="hilal-combobox__listbox" role="listbox">
          {filtered.length === 0 ? (
            <li className="hilal-combobox__empty">{emptyMessage}</li>
          ) : (
            filtered.map((opt, i) => (
              <li
                key={opt.value}
                id={`${listboxId}-${i}`}
                role="option"
                aria-selected={opt.value === value}
                aria-disabled={opt.disabled}
                className={cn(
                  'hilal-combobox__option',
                  i === activeIndex && 'hilal-combobox__option--active',
                )}
                onMouseDown={(e) => { e.preventDefault(); commit(opt); }}
                onMouseEnter={() => setActiveIndex(i)}
              >
                {opt.label}
              </li>
            ))
          )}
        </ul>
      ) : null}
      {message ? <p className="hilal-field__hint">{message}</p> : null}
    </div>
  );
});

// packages/angular/src/components/combobox.component.ts
import {
  Component, Input, Output, EventEmitter, ChangeDetectionStrategy,
  ElementRef, HostListener, signal, computed, inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export interface HilalComboboxOption {
  value: string;
  label: string;
  disabled?: boolean;
}

@Component({
  selector: 'hilal-combobox',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="fieldClasses()" [attr.data-state]="state()">
      <label *ngIf="label" class="hilal-field__label" [attr.for]="inputId">{{ label }}</label>
      <div class="hilal-field__control hilal-combobox__control">
        <input
          class="hilal-input hilal-combobox__input"
          [id]="inputId"
          role="combobox"
          [attr.aria-expanded]="open()"
          [attr.aria-controls]="inputId + '-listbox'"
          aria-autocomplete="list"
          [placeholder]="placeholder"
          [value]="query()"
          [disabled]="disabled"
          (input)="onInput($event)"
          (focus)="open.set(true)"
          (keydown)="onKey($event)"
        />
        <span class="hilal-select__chevron" aria-hidden="true">▾</span>
      </div>
      <ul *ngIf="open() && !disabled" [id]="inputId + '-listbox'" class="hilal-combobox__listbox" role="listbox">
        <li *ngIf="filtered().length === 0" class="hilal-combobox__empty">{{ emptyMessage }}</li>
        <li *ngFor="let opt of filtered(); let i = index"
          [id]="inputId + '-listbox-' + i"
          role="option"
          [attr.aria-selected]="opt.value === value"
          [attr.aria-disabled]="opt.disabled"
          [class]="optionClass(i)"
          (mousedown)="$event.preventDefault(); commit(opt)"
          (mouseenter)="activeIndex.set(i)"
        >{{ opt.label }}</li>
      </ul>
      <p *ngIf="message()" class="hilal-field__hint">{{ message() }}</p>
    </div>
  `,
})
export class HilalComboboxComponent {
  @Input() options: HilalComboboxOption[] = [];
  @Input() value = '';
  @Input() label?: string;
  @Input() hint?: string;
  @Input() error?: string;
  @Input() placeholder = 'Select…';
  @Input() disabled = false;
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() emptyMessage = 'No results';
  @Input() inputId = `hilal-cb-${Math.random().toString(36).slice(2, 9)}`;
  @Output() valueChange = new EventEmitter<string>();

  protected readonly query = signal('');
  protected readonly open = signal(false);
  protected readonly activeIndex = signal(0);

  private readonly host = inject(ElementRef<HTMLElement>);

  protected readonly fieldClasses = computed(
    () => `hilal-field hilal-combobox hilal-field--${this.size}`,
  );
  protected readonly state = computed(() =>
    this.error ? 'error' : this.disabled ? 'disabled' : 'default',
  );
  protected readonly message = computed(() => this.error ?? this.hint ?? '');

  protected readonly filtered = computed(() => {
    const q = this.query().toLowerCase();
    if (!q) return this.options;
    return this.options.filter((o) => o.label.toLowerCase().includes(q));
  });

  ngOnInit(): void {
    const sel = this.options.find((o) => o.value === this.value);
    this.query.set(sel?.label ?? '');
  }

  protected onInput(e: Event): void {
    const v = (e.target as HTMLInputElement).value;
    this.query.set(v);
    this.open.set(true);
    this.activeIndex.set(0);
  }

  protected onKey(e: KeyboardEvent): void {
    const list = this.filtered();
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      this.open.set(true);
      this.activeIndex.update((i) => Math.min(i + 1, list.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      this.activeIndex.update((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const opt = list[this.activeIndex()];
      if (opt) this.commit(opt);
    } else if (e.key === 'Escape') {
      this.open.set(false);
    }
  }

  protected commit(opt: HilalComboboxOption): void {
    if (opt.disabled) return;
    this.value = opt.value;
    this.query.set(opt.label);
    this.open.set(false);
    this.valueChange.emit(opt.value);
  }

  protected optionClass(i: number): string {
    return i === this.activeIndex()
      ? 'hilal-combobox__option hilal-combobox__option--active'
      : 'hilal-combobox__option';
  }

  @HostListener('document:mousedown', ['$event'])
  protected onDocClick(e: MouseEvent): void {
    if (!this.host.nativeElement.contains(e.target as Node)) this.open.set(false);
  }
}
