// packages/react/src/components/toast.tsx
import {
  createContext, useContext, useState, useCallback, useEffect, useRef,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { cn } from '../utils/cn.js';

export type ToastTone = 'info' | 'success' | 'warning' | 'danger';
export type ToastPosition = 'top-start' | 'top' | 'top-end' | 'bottom-start' | 'bottom' | 'bottom-end';

export interface Toast {
  id: string;
  tone?: ToastTone;
  title?: ReactNode;
  description?: ReactNode;
  icon?: ReactNode;
  durationMs?: number;
}

interface ToastContextValue {
  toast: (t: Omit<Toast, 'id'>) => string;
  dismiss: (id: string) => void;
}

const ToastContext = createContext<ToastContextValue | null>(null);

export function useToast(): ToastContextValue {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error('useToast must be used inside <ToastProvider>');
  return ctx;
}

export interface ToastProviderProps {
  position?: ToastPosition;
  children: ReactNode;
  /** Defaults to 5000ms. Set 0 for persistent toasts. */
  defaultDurationMs?: number;
}

export function ToastProvider({
  position = 'bottom-end', children, defaultDurationMs = 5000,
}: ToastProviderProps) {
  const [toasts, setToasts] = useState<Toast[]>([]);
  const timers = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());

  const dismiss = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
    const t = timers.current.get(id);
    if (t) { clearTimeout(t); timers.current.delete(id); }
  }, []);

  const toast = useCallback((t: Omit<Toast, 'id'>): string => {
    const id = `t-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const duration = t.durationMs ?? defaultDurationMs;
    setToasts((prev) => [...prev, { ...t, id }]);
    if (duration > 0) {
      timers.current.set(id, setTimeout(() => dismiss(id), duration));
    }
    return id;
  }, [defaultDurationMs, dismiss]);

  useEffect(() => () => { timers.current.forEach(clearTimeout); }, []);

  const region =
    typeof document !== 'undefined' ? createPortal(
      <div className="hilal-toast-region" data-position={position} role="region" aria-label="Notifications">
        {toasts.map((t) => (
          <div key={t.id} className={cn('hilal-toast', t.tone && `hilal-toast--${t.tone}`)} role="status">
            {t.icon ? <span className="hilal-toast__icon" aria-hidden>{t.icon}</span> : null}
            <div className="hilal-toast__body">
              {t.title       ? <p className="hilal-toast__title">{t.title}</p> : null}
              {t.description ? <p className="hilal-toast__desc">{t.description}</p> : null}
            </div>
            <button type="button" className="hilal-toast__close" aria-label="Dismiss" onClick={() => dismiss(t.id)}>×</button>
          </div>
        ))}
      </div>,
      document.body,
    ) : null;

  return (
    <ToastContext.Provider value={{ toast, dismiss }}>
      {children}
      {region}
    </ToastContext.Provider>
  );
}

// packages/angular/src/components/toast.component.ts
import { Injectable, signal, computed, Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type HilalToastTone = 'info' | 'success' | 'warning' | 'danger';
export type HilalToastPosition =
  'top-start' | 'top' | 'top-end' | 'bottom-start' | 'bottom' | 'bottom-end';

export interface HilalToast {
  id: string;
  tone?: HilalToastTone;
  title?: string;
  description?: string;
  icon?: string;
  durationMs?: number;
}

@Injectable({ providedIn: 'root' })
export class HilalToastService {
  private readonly _toasts = signal<HilalToast[]>([]);
  readonly toasts = this._toasts.asReadonly();
  position: HilalToastPosition = 'bottom-end';
  defaultDurationMs = 5000;

  private timers = new Map<string, ReturnType<typeof setTimeout>>();

  show(t: Omit<HilalToast, 'id'>): string {
    const id = `t-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const duration = t.durationMs ?? this.defaultDurationMs;
    this._toasts.update((all) => [...all, { ...t, id }]);
    if (duration > 0) {
      this.timers.set(id, setTimeout(() => this.dismiss(id), duration));
    }
    return id;
  }

  dismiss(id: string): void {
    this._toasts.update((all) => all.filter((t) => t.id !== id));
    const timer = this.timers.get(id);
    if (timer) { clearTimeout(timer); this.timers.delete(id); }
  }
}

@Component({
  selector: 'hilal-toast-region',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="hilal-toast-region" [attr.data-position]="svc.position" role="region" aria-label="Notifications">
      <div *ngFor="let t of toasts()" [class]="toastClass(t)" role="status">
        <span *ngIf="t.icon" class="hilal-toast__icon" aria-hidden="true">{{ t.icon }}</span>
        <div class="hilal-toast__body">
          <p *ngIf="t.title" class="hilal-toast__title">{{ t.title }}</p>
          <p *ngIf="t.description" class="hilal-toast__desc">{{ t.description }}</p>
        </div>
        <button type="button" class="hilal-toast__close" aria-label="Dismiss" (click)="svc.dismiss(t.id)">×</button>
      </div>
    </div>
  `,
})
export class HilalToastRegionComponent {
  protected readonly toasts;
  constructor(public readonly svc: HilalToastService) {
    this.toasts = computed(() => this.svc.toasts());
  }
  protected toastClass(t: HilalToast): string {
    return t.tone ? `hilal-toast hilal-toast--${t.tone}` : 'hilal-toast';
  }
}
